### ISSUE TITLE
Fixing Build Issue In Rider

### ISSUE THREAD

**Issue by khalidabuhakmeh** [albilaga/RefitSample#1]
👋 Hi,

I have some good news and bad news.

The good news is you can get it to build in JetBrains Rider. You'll need to change the `MSBuild` tool under **preferences**.

![image](https://user-images.githubusercontent.com/228256/104612689-7aa7f000-5654-11eb-9a51-9f1e0204b2f4.png)

You need to set this to the following version of `/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/`

You will also need to change the `RefitSample.Android` project to target `v10.0`.

```xml
    <TargetFrameworkVersion>v10.0</TargetFrameworkVersion>
```

After doing those two things, your solution should build in Rider.

![image](https://user-images.githubusercontent.com/228256/104613510-4da80d00-5655-11eb-96e4-ac2ce78687fd.png)

As you can probably tell already, the bad news for Rider users is VS Mac ships with its own version of MSBuild that is not the same version that ships with Mono proper.

I hope this helps.

Khalid
JetBrains Developer Advocate

**Comment by albilaga** [comment]
Aha so it is because custom MSBuild. Thank you @khalidabuhakmeh . Do you know the downsides using this MSbuild compared with MSBuild from mono?

**Comment by khalidabuhakmeh** [comment]
There shouldn't be a down side locally, but you might have issues recreating the build in a CI environment.

**Comment by albilaga** [comment]
Ah I see.. Yep. No plan to use CI for now. Thanks a lot...
